---
- name: install packages
  apt:
    pkg: '{{ item }}'
    install_recommends: no
  with_items:
    - unzip

- name: set facts
  set_fact:
    tomcat_webapps_dir: /var/lib/tomcat8/webapps
    motd_dir: /etc/update-motd.d

- name: setup database - create user odk
  command: psql -c "CREATE USER odk WITH UNENCRYPTED PASSWORD 'odk';"
  become_user: postgres

- name: setup database - create database odk
  command: psql -c "CREATE DATABASE odk WITH OWNER odk;"
  become_user: postgres

- name: setup database - grant on database odk
  command: psql -c "GRANT ALL PRIVILEGES ON DATABASE odk TO odk;"
  become_user: postgres

- name: setup database - create schema odk
  command: psql -c "CREATE SCHEMA odk;" odk
  become_user: postgres

- name: setup database - grant on schema odk.odk
  command: psql -c "GRANT ALL PRIVILEGES ON SCHEMA odk TO odk;" odk
  become_user: postgres

- name: Clean webapps dir
  file:
    state: absent
    path: "{{ tomcat_webapps_dir }}/"

- name: Create webapps dir
  file:
    state: directory
    path: "{{ tomcat_webapps_dir }}/ROOT"

- name: Deploy Aggregate
  unarchive:
    src: 'ROOT.war'
    dest: '{{ tomcat_webapps_dir }}/ROOT'

- name: Clean existing motd scripts
  file:
    state: absent
    path: "{{ motd_dir }}/"

- name: copy motd scripts
  copy:
    src: 'motd/'
    dest: '{{ motd_dir }}'
    mode: 0755
