---
- name: install packages
  apt:
    pkg: '{{ item }}'
    install_recommends: no
  with_items:
    - unzip

- name: set facts
  set_fact:
    tomcat_webapps_dir: /var/lib/tomcat8/webapps
    motd_dir: /etc/update-motd.d

- name: setup database - create user aggregate
  command: psql -c "CREATE USER aggregate WITH UNENCRYPTED PASSWORD 'aggregate';"
  become_user: postgres

- name: setup database - create database aggregate
  command: psql -c "CREATE DATABASE aggregate WITH OWNER aggregate;"
  become_user: postgres

- name: setup database - grant on database aggregate
  command: psql -c "GRANT ALL PRIVILEGES ON DATABASE aggregate TO aggregate;"
  become_user: postgres

- name: setup database - create schema aggregate
  command: psql -c "CREATE SCHEMA aggregate;" aggregate
  become_user: postgres

- name: setup database - grant on schema aggregate.aggregate
  command: psql -c "GRANT ALL PRIVILEGES ON SCHEMA aggregate TO odk;" aggregate
  become_user: postgres

- name: Clean webapps dir
  file:
    state: absent
    path: "{{ tomcat_webapps_dir }}/"

- name: Create webapps dir
  file:
    state: directory
    path: "{{ tomcat_webapps_dir }}/ROOT"

- name: Deploy Aggregate
  unarchive:
    src: 'ROOT.war'
    dest: '{{ tomcat_webapps_dir }}/ROOT'

- name: Clean existing motd scripts
  file:
    state: absent
    path: "{{ motd_dir }}/"

- name: copy motd scripts
  copy:
    src: 'motd/'
    dest: '{{ motd_dir }}'
    mode: 0755
